### ISSUE TITLE
SLP History Fails to Populate

### ISSUE THREAD

**Issue by JettScythe** [simpleledger/Electron-Cash-SLP#39] opened 2019-02-18 06:23 UTC
Importing seed from BadgerWallet 0.2.0 into SLP-EC 3.4.3 using m/44'/145'/0' as the path.
As title states, the SLP History tab fails to populate, but going into the details of a tx clearly shows the SLP in the op_return.

Running Windows 10. Haven't tried on another device yet.

**Comment by jcramer** [comment] 2019-02-18 14:06
Hi Jeff, 

I tried to reproduce this problem using the latest code.  I imported my Badger Wallet seed using m/44'/145'/0' and everything populated for tokens.  

Please note Version 3.4.3 had some bugs that are addressed now and we will roll out a new release very soon.  

Thanks for the report and let us know if you have any other issues.  We'll let you know as soon as the next build is released.

**Comment by jcramer** [comment] 2019-03-07 14:57
@JettScythe I am going to close this issue because I believe it is resolved.  If this is still a problem for you with the latest release let me know and we'll reopen.

**Closed by jcramer** 2019-03-07 14:57 UTC
