### ISSUE TITLE
Transaction contains an SLP input that is unknown to this wallet (missing from slp_txo).

### ISSUE THREAD

**Issue by kharri1073** [simpleledger/Electron-Cash-SLP#117] opened 2020-01-08 17:14 UTC
I can't send any acquired slp tokens from the app, I receive the above message every time I try to send to another address from the Electron-Cash-SLP wallet.

I have tried to send one token and also the max amount and I receive this error every time.

"Transaction contains an SLP input that is unknown to this wallet (missing from slp_txo)."

Electron Cash SLP 3.6.1 - Linux AppImage 

![Screenshot from 2020-01-08 12-09-32](https://user-images.githubusercontent.com/972280/71999960-4fecb580-3210-11ea-9fbb-98e69f275db5.png)

**Comment by jcramer** [comment] 2020-01-08 17:28
This is a bug in the EC SLP wallet software that occurs when a graph search server fails, this is due to a bug in the graph search server. 

 When a graph search server fails it can corrupt the wallet, so here are the steps which might allow you to recover the corrupted wallet file and make new transactions, assuming that the graph search server is still not in a failed state:

1. Make sure you have backed up your wallet's seed in a safe place.

2. Make sure Graph Search is turned on and try to use `gs.fountainhead.cash` as the default server (currently `gs.simpleledger.io` just redirects there so it may be more direct.  To select a server and enable graph search, go to the Network dialog (green dot, lower right) and select the "Tokens Tab".

3. Close Electron Cash SLP

4. Move the malfunctioning wallet file out of the `~/.electron-cash/wallets` directory, this way it will not automatically open in the next step.

5. Open Electron Cash SLP

6. Create a new wallet file, and restore your seed, then add SPICE token back to the wallet and monitor the "SLP History" tab for validation progress.

**Comment by kharri1073** [comment] 2020-01-08 18:21
Hi @jcramer thank you for your response!

I followed your instructions and everything looks to be validating again.

Once I saw SOUR tokens were valid, I tried to create a transaction with them. Again, I received the same error.

![Screenshot from 2020-01-08 13-12-30](https://user-images.githubusercontent.com/972280/72004590-b4f8d900-3219-11ea-8e2a-5807bd313a19.png)

A few minutes later, SPICE tokens were validated. Again, I tried to create a transaction but was greeted with the same error.

I can confirm that my wallet is using the https://gs.fountainhead.cash graph search server.

Let me know if I can help debug with anything else.

Thank you.

**Comment by jcramer** [comment] 2020-01-08 18:25
ok, I can try to take a look at the issue soon, but it may be a few days.

**Comment by jcramer** [comment] 2020-01-08 18:27
Can verify whether or not every SLP transaction made in the normal History tab is showing up in the  "SLP History" tab?

**Comment by kharri1073** [comment] 2020-01-08 18:52
There looks to be an additional 27 SLP transactions (546 satoshi transactions) in the history tab than in the SLP hisory tab. There's over 400 transactions, many from faucets, so counting in the GUI is a little hard. Are there any commands that can be useful from the console?

**Comment by jcramer** [comment] 2020-01-08 18:53
Taking a look at the code now, are you able to run EC SLP from source?

**Comment by jcramer** [comment] 2020-01-08 19:25
I pushed a commit 9e5f3af which should fix the part where not ALL SLP transactions are shown in the SLP history.  If you could try running from the source that would be really helpful in diagnosing the root of the problem.

**Comment by kharri1073** [comment] 2020-01-08 19:27
Thank you, I will try to run from source later this evening.

**Comment by kharri1073** [comment] 2020-01-09 03:40
Hi again,

Apologies, I'm having issues running from source.

I believe I'm narrowing down to a sort of workaround for my issue.

Here's screenshots of three transactions previews just prior to sign.

The first two sign successfully but the last doesn't sign and errors out with "Transaction contains an SLP input that is unknown to this wallet (missing from slp_txo)."

![signs-some](https://user-images.githubusercontent.com/972280/72035761-c916f780-3266-11ea-8722-168ceb5c1bf1.png) 810 tokens can sign
![signs-all](https://user-images.githubusercontent.com/972280/72035768-cc11e800-3266-11ea-9868-8a48f1c7525d.png) all tokens with a small additional bch addition

![cant-sign](https://user-images.githubusercontent.com/972280/72035774-cf0cd880-3266-11ea-967b-eafe2cbad6c7.png) 811 tokens can't sign

If you take a look at the first two, they both have a yellow change address specified in the inputs and the outputs. The one that doesn't sign, does not.

 If it can help, I'd be happy to share addresses outside of a public forum.

Thank you again!

**Comment by jcramer** [comment] 2020-01-09 15:35
Ok, thank you for that.  I can see the problem now.  The wallet is allowing spending of an 0 value input from a different token ID.  I need to add a special condition to the final SLP checker to allow spending of 0 output token outputs from other token Ids.

**Comment by jcramer** [comment] 2020-01-09 21:14
@kharri1073 please try this pre-release version with patches applied:
https://github.com/simpleledger/Electron-Cash-SLP/releases/tag/3.6.2-dev1

**Comment by kharri1073** [comment] 2020-01-09 22:55
Thanks so much@jcramer, that fixed it. One transaction was sent and confirmed. Another few problematic transactions were signed without an issue.

**Comment by jcramer** [comment] 2020-01-09 23:00
Awesome glad to hear it is resolved,  thanks for the help finding the root cause.  Closing this now, let me know if you have any more issues.

**Closed by jcramer** 2020-01-09 23:00 UTC
Labels: bug
