### ISSUE TITLE
Wallet auto-combines BCH coins when sending SLP tokens

### ISSUE THREAD

**Issue by imaginaryusername** [simpleledger/Electron-Cash-SLP#27] opened 2018-10-09 04:13 UTC
If I send an SLP token, aside from the SLP UTXO the wallet seems to automatically combine all the rest of my BCH in the same wallet as input ("consolidating" them). While the change is still correct, this cost me unnecessary fees as well as reduce my privacy. Please fix.

**Comment by jcramer** [comment] 2018-10-09 13:44
I agree this needs to be fixed. The reason we chose to sweep all BCH coins in SLP transactions was that it was simple to implement.  A proper solution will require some work in the coin selection parts of code.

**Comment by imaginaryusername** [comment] 2019-02-16 22:50
Did anyone look into this? It's kinda important not just for privacy but for security too, since it means a wallet will only have one BCH output at any given time... if I send two tokens from it one after the other, the later one involuntarily becomes an unconfirmed chain, without being able to use another BCH coin for fees; so it reduces security of transactions slightly.

**Comment by cculianu** [comment] 2019-02-17 10:50
I could take a look at porting Neil’s coinchooser logic over to the SLP coin choosing logic. I haven’t looked at it yet but with any luck it might not be too bad. Thanks for reminding.

**Comment by emergent-reasons** [comment] 2019-03-07 00:37
Is this the cause of the high sats/byte fees that I often need to use when sending from my slp wallet? I wanted to advertise "instantaneous and nearly free" when I passed on "The SLP Torch" just now on twitter but I ended up having to use 5sats/byte so I skipped that part.

**Comment by jcramer** [comment] 2019-03-07 04:03
@emergent-reasons 5 sats/byte sounds unusually high and this is not the intended or accepted behavior of the current coin chosen logic.  I'll look into this tomorrow and circle back here.

**Comment by emergent-reasons** [comment] 2019-03-07 04:07
Ok thank you. FYI I have had to do over 10 in the past.

Probably 1 as well but I can’t be sure about that.

**Comment by emergent-reasons** [comment] 2019-03-13 16:13
@jcramer FYI I got confirmation from an EC-SLP user in Japan that they also got surprised and worried by required fee being up around 10 sats sometimes. They even said that they tried the next day after giving up and it was back to 1. No idea how that happened. Maybe they sent another transaction in the meantime that consolidated or...???

If I should file a different issue, I would be happy to do that. This consolidation issue just sounds like it might be the root cause of the fee weirdness.

**Comment by imaginaryusername** [comment] 2019-03-13 16:25
@emergent-reasons from what I can tell it's almost always a consolidation issue, especially if you fed BCH to the wallet multiple times, spent BCH from the same wallet, or simply have multiple coins of the same token. This can also potentially be a problem if one gets >15 (or 20?) copies of a token and the op_return no longer fits all in a single transaction, and should be fixed asap.

**Comment by jcramer** [comment] 2019-04-18 20:55
This should be fixed here:
https://github.com/simpleledger/Electron-Cash-SLP/commit/422d61419692c52e2a80a7436443be2d719b3a6e

**Closed** 2019-04-18 20:58 UTC
Labels: Priority
